### ISSUE TITLE
Detection spontaneous client disconnection

### ISSUE THREAD

**Issue by anotherstarburst** [sysid/sse-starlette#76] opened 2023-09-14 07:05 UTC
Thanks for building this @sysid ! Very useful and works like a charm. 

I'm using this in a project in place of a websocket (as I only need to send data to the client). One area I'm having trouble with is identifying sudden disconnections - e.g. browser tab closes. I expect I'm just misunderstanding the mechanism to detect this.

## What I expect to happen

When I spontaneously close a connection to the SSE handler I expect an `asyncio.CancelledError` exception to be raised

## What actually happens

No exception is raised

## Steps to reproduce:

1. Run: `$ uvicorn main:app --reload`
2. Open :  http://localhost:8000/
3. Observe the console - which will print "yielding some message {some number}"
4. Close the browser tab from (2)
5. Continue to see the console messages updating

## Minimally reproducible example 

```python
import asyncio
import uvicorn
from starlette.applications import Starlette
from starlette.routing import Route
from sse_starlette.sse import EventSourceResponse


async def numbers(request):
    try:
        index = 0
        while True:
            index += 1
            await asyncio.sleep(1)
            if await request.is_disconnected():
                await asyncio.sleep(5)
                raise asyncio.CancelledError("Client disconnected")
            print("yielding some message", index)
            yield dict(data="Some message")
    except asyncio.CancelledError as e:
        await asyncio.sleep(5)
        print("CancelledError", e)
    except asyncio.TimeoutError as e:
        await asyncio.sleep(5)
        print("TimeoutError", e)


async def sse(request):
    gen = numbers(request)
    return EventSourceResponse(
        gen,
        ping=1,
    )


routes = [Route("/", endpoint=sse)]

app = Starlette(debug=True, routes=routes)

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000, log_level="info")
```

Do you have any clues as to where I might be going wrong?

**Comment by sysid** [comment] 2023-09-15 15:09
@anotherstarburst , unfortunately I cannot reproduce your observations.
When I run your example it works as expected, i.e. last console message: "CancelledError". No messages after that.

**Comment by anotherstarburst** [comment] 2023-09-15 17:59
Thanks for trying!

So, the tab closes, but the download is handled in a separate browser context so carries on. My minimally reproducible example doesn't demonstrate the problem I'm seeing with my actual set up :/ 

I'll close this one and try to put together a better minimally reproducible example :)

**Comment by anotherstarburst** [comment] 2023-09-15 18:49
Ah, I forgot the key detail - a small delay! 

I realise the example is totally artificial. What I'm trying to figure out is how to get something like a websocket onclose event when a session closes. The delay is simulating the onclose event logic - with the print statement being the final step.

**Comment by sysid** [comment] 2023-09-16 07:36
Adding `await asyncio.sleep(1)` in the `except asyncio.CancelledError as e:` block delays the exception handling and allows a context switch. Since this coroutine is already canceled at this point, any further asynchronous operations like await asyncio.sleep(1) will not execute.

However, I still cannot reproduce a continuation of console messages. Only the "CancelledError" does not show up for the reason mentioned above.

If you do a synchronous sleep it will again work as excpected because there is no context switch involved.  

I will close this now since I do not see any issues with sse-starlette's behavior.

**Closed by sysid** 2023-09-16 07:36 UTC
